/// Financial Strategy Model
/// Structured multi-dimensional strategy generated by AI
class FinancialStrategy {
  final SpendingControl spendingControl;
  final SavingsPlan savingsPlan;
  final TaxStrategy taxStrategy;
  final RiskMitigation riskMitigation;
  final LiquidityPlan liquidityPlan;
  final DateTime generatedAt;

  FinancialStrategy({
    required this.spendingControl,
    required this.savingsPlan,
    required this.taxStrategy,
    required this.riskMitigation,
    required this.liquidityPlan,
    required this.generatedAt,
  });

  factory FinancialStrategy.fromText(String text) {
    // Parse AI-generated strategy text into structured format
    final lines = text.split('\n').where((l) => l.trim().isNotEmpty).toList();
    
    return FinancialStrategy(
      spendingControl: SpendingControl(actions: _extractSection(lines, 'spending')),
      savingsPlan: SavingsPlan(actions: _extractSection(lines, 'savings')),
      taxStrategy: TaxStrategy(actions: _extractSection(lines, 'tax')),
      riskMitigation: RiskMitigation(actions: _extractSection(lines, 'risk')),
      liquidityPlan: LiquidityPlan(actions: _extractSection(lines, 'liquidity')),
      generatedAt: DateTime.now(),
    );
  }

  static List<String> _extractSection(List<String> lines, String keyword) {
    return lines
        .where((l) => l.toLowerCase().contains(keyword))
        .map((l) => l.trim())
        .toList();
  }

  List<String> getAllActions() {
    return [
      ...spendingControl.actions,
      ...savingsPlan.actions,
      ...taxStrategy.actions,
      ...riskMitigation.actions,
      ...liquidityPlan.actions,
    ];
  }
}

class SpendingControl {
  final List<String> actions;
  SpendingControl({required this.actions});
}

class SavingsPlan {
  final List<String> actions;
  SavingsPlan({required this.actions});
}

class TaxStrategy {
  final List<String> actions;
  TaxStrategy({required this.actions});
}

class RiskMitigation {
  final List<String> actions;
  RiskMitigation({required this.actions});
}

class LiquidityPlan {
  final List<String> actions;
  LiquidityPlan({required this.actions});
}
