import 'package:hive_flutter/hive_flutter.dart';

part 'financial_decision.g.dart';

/// Financial Decision Model
/// Represents an actionable decision generated by the AI system
@HiveType(typeId: 6)
class FinancialDecision {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final String type;

  @HiveField(2)
  final String message;

  @HiveField(3)
  final int priority; // 1-10, 8+ = urgent notification

  @HiveField(4)
  final DateTime timestamp;

  @HiveField(5)
  final Map<String, dynamic> metadata;

  @HiveField(6)
  final bool dismissed;

  @HiveField(7)
  final bool accepted;

  FinancialDecision({
    required this.id,
    required this.type,
    required this.message,
    required this.priority,
    required this.timestamp,
    this.metadata = const {},
    this.dismissed = false,
    this.accepted = false,
  });

  FinancialDecision copyWith({
    String? id,
    String? type,
    String? message,
    int? priority,
    DateTime? timestamp,
    Map<String, dynamic>? metadata,
    bool? dismissed,
    bool? accepted,
  }) {
    return FinancialDecision(
      id: id ?? this.id,
      type: type ?? this.type,
      message: message ?? this.message,
      priority: priority ?? this.priority,
      timestamp: timestamp ?? this.timestamp,
      metadata: metadata ?? this.metadata,
      dismissed: dismissed ?? this.dismissed,
      accepted: accepted ?? this.accepted,
    );
  }
}

/// Decision Types
class DecisionType {
  static const String spendingAlert = 'spending_alert';
  static const String savingsOpportunity = 'savings_opportunity';
  static const String taxOptimization = 'tax_optimization';
  static const String riskWarning = 'risk_warning';
  static const String cashflowAlert = 'cashflow_alert';
  static const String budgetAdjustment = 'budget_adjustment';
  static const String lifeEvent = 'life_event';
  static const String milestone = 'milestone';
  static const String anomalyDetected = 'anomaly_detected';
  static const String coachAction = 'coach_action';
}
